survey_maker/constructor_app/urls.py
from django.urls import path
from constructor_app import views

app_name = 'constructor_app'


urlpatterns = [
    path('', views.main_view, name='index'),
    path('companies/', views.CompaniesListView.as_view(), name='companies'),
    path('company/<int:pk>/', views.CompanyDetailView.as_view(), name='company'),
    path('create/', views.CompanyCreateView.as_view(), name='create'),
    path('landing/', views.landing_view),

]

survey_maker/survey_maker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maker_app.urls', namespace='maker')),
    path('user/', include('user_app.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

survey_maker/user_app/urls.py
from django.urls import path
from user_app import views
from django.contrib.auth.views import LogoutView


app_name = 'user_app'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.RegisterUserCreateView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', views.UsersListView.as_view(), name='users'),
    path('adduser/', views.UserCreateView.as_view(), name='adduser'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user'),

]

survey_maker/constructor_app/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from users_app.models import SurveyUser


# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=64, unique=True)
    logo = models.ImageField(null=True, blank=True, upload_to='company')
    user = models.ManyToManyField(SurveyUser, blank=True)

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'компании'

    def __str__(self):
        return self.name


class QuestionType(models.Model):
    question_type_name = models.CharField(max_length=64)

    class Meta:
        verbose_name = 'Тип вопроса'
        verbose_name_plural = 'типы вопросов'

    def __str__(self):
        return self.question_type_name


class Question(models.Model):
    question_name = models.CharField(max_length=128)
    question_type = models.ForeignKey(QuestionType, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'вопросы'

    def __str__(self):
        return self.question_name


class Page(models.Model):
    greeting = models.CharField(max_length=64, null=True, blank=True)
    instruction = models.CharField(max_length=64, null=True, blank=True)
    final_page = models.CharField(max_length=64, null=True, blank=True)
    page_number = models.PositiveIntegerField(null=True, blank=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Страница'
        verbose_name_plural = 'Страницы'

    def __str__(self):
        return self.question_name


class Survey(models.Model):
    name = models.CharField(max_length=64)
    company = models.ManyToManyField(Company)
    start_date = models.DateField()
    end_date = models.DateField()
    page = models.ForeignKey(Page, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'опросы'

    def __str__(self):
        return self.name


class Structure(MPTTModel):
    company = models.ManyToManyField(Company)
    department = models.CharField(max_length=64, unique=True)
    head_of_department = models.CharField(max_length=64, null=True, blank=True)
    code = models.PositiveIntegerField(null=True, blank=True)
    workers = models.PositiveIntegerField(null=True, blank=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class Meta:
        verbose_name = 'Структура'
        verbose_name_plural = 'Структуры'

    class MPTTMeta:
        order_insertion_by = ['department']

    def __str__(self):
        return self.department

survey_maker/constructor_app/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from .forms import ContactForm
from django.views.generic import ListView, DetailView, CreateView


from .models import Structure, Company


# Create your views here.
def main_view(request):
    pass
    return render(request, 'constructor:index')


def landing_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            # last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']

            send_mail(
                'Contact message',
                f'Ваш сообщение "{subject}" принято',
                'id2k1149@gmail.com',
                [email],
                fail_silently=True,
            )

            return HttpResponseRedirect(reverse('constructor:index'))

        else:
            return render(request, 'constructor_app/landing.html', context={'form': form})
    else:
        form = ContactForm()
        return render(request, 'constructor_app/landing.html', context={'form': form})


# ListView
class CompaniesListView(ListView):
    model = Company
    template_name = 'constructor_app/companies.html'


# DetailView
class CompanyDetailView(DetailView):
    model = Company
    template_name = 'constructor_app/company.html'


# CreateView
class CompanyCreateView(CreateView):
    fields = ('name',)
    model = Company
    success_url = reverse_lazy('constructor:companies')
    template_name = 'constructor_app/create.html'

    # def someview(request):
    #     form = SomeForm(..)
    #
    #     if some_condition:
    #         name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': "form-control rounded-0"}))
    #         form.fields['email'].widget.attrs['placeholder'] = instance.email

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        return super().form_valid(form)

survey_maker/constructor_app/templates/constructor_app/companies.html
{% extends "base.html" %}
{% block title %} Компании {% endblock %}

{% block content %}
<div id="content">

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                       aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                    <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Settings
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                        Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->

    <!-- Begin Page Content -->
    <div class="container-fluid">


        <!-- Page Heading -->
        <i class="fa fa-sitemap"> Управление</i>
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0" style="color:black;">Компании</h1>
            <a href="{% url 'constructor:create' %}"
               class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-sm text-white-50"></i>СОЗДАТЬ
                КОМПАНИЮ</a>
        </div>

        <!-- Content Row -->

        <div class="row col-md-12">
            {% for item in object_list %}

            <!-- Companies Cards  -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                {% if item.logo %}
                                <img src="{{item.logo.url}}" width="40">
                                {% else %}
                                <i class="fas fa-sitemap fa-2x text-gray-300"> </i>
                                {% endif %}
                            </div>
                            <div class="col mr-2"  style="padding-left: 10px;">
                                <a href="{% url 'constructor:company' pk=item.pk %}">
                                    <div class="font-weight-bold text-primary text-uppercase mb-1">{{ item.name }}</div>
                                </a>
                            </div>

                        </div>
                        <br>
                        <br>


                            <div class="row">
                                <div class="ant-col ant-col-8" style="padding-left: 12.5px; padding-right: 12.5px; text-align:center;">
                                    <div class="item" style="cursor: pointer;">
                                        <div class="value" style="color:black;">3930</div>
                                        <div class="label">Структуры</div>
                                    </div>
                                </div>
                                <div class="ant-col ant-col-8" style="text-align:center;">
                                    <div class="item" style="cursor: pointer;">
                                        <div class="value" style="color:black;">10</div>
                                        <div class="label">Сотрудники</div>
                                    </div>
                                </div>
                                <div class="ant-col ant-col-8" style="padding-left: 12.5px; padding-right: 12.5px; text-align:center;">
                                    <div class="item" style="cursor: pointer;">
                                        <div class="value" style="color:black;">32</div>
                                        <div class="label">Опросы</div>
                                    </div>
                                </div>
                            </div>

                        <!--                        <div class="row no-gutters align-items-center">-->
                        <!--                            <div class="col mr-3">-->
                        <!--                                <a href="#">-->
                        <!--                                    <div class="font-weight-bold text-primary text-uppercase mb-1">Структуры</div>-->
                        <!--                                </a>-->
                        <!--                                <div class="h5 mb-0 font-weight-bold text-gray-800"></div>-->
                        <!--                            </div>-->
                        <!--                            <div class="col mr-3">-->
                        <!--                                <a href="#">-->
                        <!--                                    <div class="mb-1">Опросы</div>-->
                        <!--                                </a>-->
                        <!--                                <div class="h5 mb-0 font-weight-bold text-gray-800"></div>-->
                        <!--                            </div>-->
                        <!--                            <div class="col mr-3">-->
                        <!--                                <a href="#">-->
                        <!--                                    <div class="font-weight-bold text-primary text-uppercase mb-1">Сотрудники</div>-->
                        <!--                                </a>-->
                        <!--                                <div class="h5 mb-0 font-weight-bold text-gray-800"></div>-->
                        <!--                            </div>-->

                        <!--                        </div>-->
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>

    </div>
    <!-- /.container-fluid -->

</div>

{% endblock %}

survey_maker/constructor_app/templates/constructor_app/company.html
{% extends "base.html" %}
{% block title %} Company {% endblock %}

          {% block content %}
           <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          {{company.name}}









        </div>
        <!-- /.container-fluid -->

      </div>

          {% endblock %}

survey_maker/constructor_app/templates/constructor_app/create.html
{% extends "base.html" %}
{% block title %} Создать компанию {% endblock %}

{% block content %}
<div id="content">

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                       aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                    <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Settings
                    </a>
                    <a class="dropdown-item" href="#">
                        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                        Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->

    <!-- Begin Page Content -->
    <div class="container-fluid">


        <!-- Page Heading -->
        <i class="fa fa-sitemap"> Компании</i>
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0" style="color:black;">Создание Компании</h1>
        </div>


        <!-- Content Row -->

        <div>
            <h1 class="h1 mb-0" style="color:black; text-align:center">Название Компании</h1>

            <div style="text-align:center;">
                <br>
                <h6>Введите название компании.</h6>
                <h6>Загрузить логотип, создать сруктуру,</h6>
                <h6>добавить пользователей вы cможете в настройках компании.</h6>
            </div>
            <form method="post" enctype="multipart/form-data" style="text-align:center;">
                {% csrf_token %}
                {# form.as_ul #}
                {% for field in form %}
                {% for error in field.errors %}
                {{error}}
                {% endfor %}
                <p placeholder="Введите название предприятия, управления…">{{field}}</p>
                {% endfor %}
                <button type="submit" class="btn btn-primary" style="text-align:center;">СОЗДАТЬ КОМПАНИЮ</button>
            </form>
            <br>
            <div style="text-align:center;">
                <a href="{% url 'constructor:companies' %}">ОТМЕНИТЬ</a>
            </div>
            <br>

        </div>


        <!-- /.container-fluid -->

    </div>

    {% endblock %}
</div>