survey_maker/survey_maker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maker_app.urls', namespace='maker')),
    path('user/', include('user_app.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

survey_maker/user_app/urls.py
from django.urls import path
from user_app import views
from django.contrib.auth.views import LogoutView


app_name = 'user_app'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.RegisterUserCreateView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', views.UsersListView.as_view(), name='users'),
    path('adduser/', views.UserCreateView.as_view(), name='adduser'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user'),

]

survey_maker/user_app/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""
    username = None
    email = models.EmailField(_('email address'), unique=True)
    avatar = models.ImageField(blank=True, upload_to='avatars')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

survey_maker/user_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label='Email',
                             widget=forms.TextInput(attrs={'placeholder': 'bruce@wayne.com',
                                                           'class': "form-control rounded-0"}))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.TextInput(attrs={'placeholder': 'At least 8 characters',
                                                              'class': "form-control rounded-0"}))
    password2 = forms.CharField(label='Подтвердить пароль',
                                widget=forms.TextInput(attrs={'class': "form-control rounded-0"}))

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

survey_maker/user_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView
from .forms import RegistrationForm
from django.views.generic import ListView, DetailView, CreateView
from .models import User


# Create your views here.
# def get_absolute_url(self):
#     return reverse('user_detail', kwargs={'pk': self.pk})


class UserLoginView(LoginView):
    template_name = 'user_app/login.html'


class RegisterUserCreateView(CreateView):
    model = User
    template_name = 'user_app/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('user:login')


# ListView
class UsersListView(ListView):
    model = User
    template_name = 'user_app/users.html'


# CreateView
class UserCreateView(LoginRequiredMixin, CreateView):
    fields = ('email', 'first_name', 'last_name', 'avatar')

    model = User
    success_url = reverse_lazy('user:users')
    template_name = 'user_app/adduser.html'

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        return super().form_valid(form)


# DetailView
class UserDetailView(UserPassesTestMixin, DetailView):
    model = User
    template_name = 'user_app/user.html'

    def test_func(self):
        return self.request.user.is_superuser

survey_maker/user_app/templates/user_app/adduser.html
{% extends "base.html" %}
{% block title %} login {% endblock %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data" style="text-align:center;">
                {% csrf_token %}

                {% for field in form %}
                {% for error in field.errors %}
                {{error}}
                {% endfor %}
                <p placeholder="Введите название ">{{field}}</p>
                {% endfor %}
                <button type="submit" class="btn btn-primary" style="text-align:center;">ДОБАВИТЬ ПОЛЬЗОВАТЕЛЯ</button>
            </form>
            <br>
            <div style="text-align:center;">
                <a href="{% url 'user:users' %}">ОТМЕНИТЬ</a>
            </div>
            <br>



</div>
{% endblock %}

survey_maker/user_app/templates/user_app/login.html
{% extends "base.html" %}
{% block title %} login {% endblock %}

{% block content %}
<div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">

        <div class="col-lg-6">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome!</h1>
                </div>
                <div class="row justify-content-md-center">
                    <form class="col-lg-6" method="post">
                        {% csrf_token %}
                        <div row><label>Email:</label></div>
                        <div class="form-group">
                            <label>{{ form.username }}</label>
                        </div>
                        <div row><label>Пароль:</label></div>
                        <div class="form-group">
                            {{ form.password }}
                        </div>
                        <button type="submit" class="btn btn-primary btn-user btn-block">Войти</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 d-none d-lg-block">
                <div class="text-center">
                    {% load static %}<img src="{% static 'bootstrap/img/laptop.png' %}" width=80%>
                </div>
        </div>
    </div>
    <hr>
            <div class="text-center">
                <a class="small" href="forgot-password.html">Забыли пароль?</a>
            </div>
            <div class="text-center">
                <a class="small" href="{% url 'user:register' %}">Зарегистрироваться!</a>
            </div>
    <hr>
    {% endblock %}

survey_maker/user_app/templates/user_app/register.html
{% extends "base.html" %}
{% block title %} Регистрация {% endblock %}

{% block content %}
<div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row align-items-center">
        <div class="col-lg-6">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Регистрация</h1>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-user btn-block">Отправить</button>
                </form>
            </div>
        </div>
        <div class="col-lg-6 d-none d-lg-block ">
            <div class="text-center">
                {% load static %}<img src="{% static 'bootstrap/img/laptop.png' %}" width=80%>
            </div>
        </div>
    </div>
    <hr>
    <div class="text-center">
        <a class="small" href="{% url 'user:login' %}">Есть аккаунт?</a>
    </div>
    <br>

    {% endblock %}

survey_maker/user_app/templates/user_app/user.html
{% extends "base.html" %}
{% block title %} Пользователь {% endblock %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="col">
        {% if user.avatar %}
        <img src="{{user.avatar.url}}" width="40">
        {% else %}
        <i class="fas fa-sitemap fa-2x text-gray-300"> </i>
        {% endif %}
    </div>
    <div class="col">
        {{ user.email }}{{ user.first_name }}{{ user.last_name }}
    </div>


</div>
{% endblock %}

survey_maker/user_app/templates/user_app/users.html
{% extends "base.html" %}
{% block title %} Пользователи {% endblock %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <i class="fa fa-sitemap"> Управление</i>
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0" style="color:black;">Пользователи</h1>
        <a href="{% url 'user:adduser' %}"
           class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-sm text-white-50"></i>
            ДОБАВИТЬ ПОЛЬЗОВАТЕЛЯ</a>
    </div>
    <!-- Content Row -->

        {% for item in object_list %}
        <!-- Users Cards  -->

        <div class="row col-md-12">


            <div class="col">
                {% if item.avatar %}
                <img src="{{item.avatar.url}}" width="40">
                {% else %}
                <i class="fas fa-sitemap fa-2x text-gray-300"> </i>
                {% endif %}
            </div>
            <div class="col">
                <a href="{% url 'user:user' pk=item.pk %}">
                {{ item.email }}{{ item.first_name }}{{ item.last_name }}
                     </a>
            </div>
        </div>

    <hr>
        {% endfor %}

</div>
<!-- /.container-fluid -->
{% endblock %}